SELECT 
  CONCAT(f_p,'_',s_p) AS 'Pars', 
  tov.s AS 'TO Pars',
  (SELECT
  SUM(QUANTITY*PRICE)
FROM basket_20190922
WHERE ORDER_ID NOT IN (SELECT
  ORDER_ID
FROM basket_20190922
WHERE PRODUCT_ID = t.s_p)
  AND PRODUCT_ID = t.f_p) AS 'TO 1 without 2',
(SELECT
  SUM(QUANTITY*PRICE)
FROM basket_20190922
WHERE ORDER_ID NOT IN (SELECT
  ORDER_ID
FROM basket_20190922
WHERE PRODUCT_ID = t.f_p)
  AND PRODUCT_ID = t.s_p) AS 'TO 2 without 1'
FROM two_2 t
LEFT JOIN (SELECT CONCAT(f.PRODUCT_ID,'_',s.PRODUCT_ID) pars, SUM(f.QUANTITY*f.PRICE+s.QUANTITY*s.PRICE) s
FROM basket_20190922 f
JOIN (SELECT  ORDER_ID,  PRODUCT_ID,  QUANTITY,  PRICE
FROM basket_20190922) s ON s.ORDER_ID = f.ORDER_ID
WHERE f.PRODUCT_ID <> s.PRODUCT_ID
GROUP BY CONCAT(f.PRODUCT_ID,'_',s.PRODUCT_ID)) tov ON CONCAT(f_p,'_',s_p) = tov.pars
LIMIT 10